server:
  port: 8000
  context-path: /springboot
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    excluded-user-agents:
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048000
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: root
    password: root
#    url: jdbc:postgresql://10.30.232.228:5432/analyticalPF
#    username: postgres
#    password: iAscpz2016
    # druid配置
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    multipart:
      enabled: true
      #上传文件大小限制
      max-file-size: 100MB
  mvc:
    view:
      prefix: /templates/ # Spring MVC view prefix.
      suffix: .html # Spring MVC view suffix.
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

mybatis:
  config: classpath:mybatis-config.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
